import { LandType, BiomeType, BiomeDepth, BiomeAddCardEnum } from './LandAndBiome';
import { AbilityType } from './EntityFeatures';
import { PhaseEnum } from './Phase';
import { EffectType } from './Effect';
import { ZoneEnum, ZoneEnumMethods, ZoneOwner, ZoneRefreshType, ZoneOwnerVisibility, ZoneOpponentVisibility } from './Zone';
import { KeywordType, Attribute } from './Keyword';
import { TargetTypeEnum, TargetableTypeSelectionEnum, BroadTargetTypeEnum, TargetMethods } from './Target';
import { NetworkProtocol } from './NetworkProtocol';
import { ConditionType, ConditionTargetType, ConditionMethods } from './Condition';
declare const _default: {
    LandType: typeof LandType;
    BiomeType: typeof BiomeType;
    BiomeDepth: typeof BiomeDepth;
    BiomeAddCardEnum: typeof BiomeAddCardEnum;
    AbilityType: typeof AbilityType;
    PhaseEnum: typeof PhaseEnum;
    KeywordType: typeof KeywordType;
    Attribute: typeof Attribute;
    ZoneEnum: typeof ZoneEnum;
    EffectType: typeof EffectType;
    ZoneEnumMethods: typeof ZoneEnumMethods;
    ZoneOwner: typeof ZoneOwner;
    ZoneRefreshType: typeof ZoneRefreshType;
    ZoneOwnerVisibility: typeof ZoneOwnerVisibility;
    ZoneOpponentVisibility: typeof ZoneOpponentVisibility;
    NetworkProtocol: typeof NetworkProtocol;
    TargetTypeEnum: typeof TargetTypeEnum;
    TargetableTypeSelectionEnum: typeof TargetableTypeSelectionEnum;
    BroadTargetTypeEnum: typeof BroadTargetTypeEnum;
    TargetMethods: typeof TargetMethods;
    ConditionType: typeof ConditionType;
    ConditionTargetType: typeof ConditionTargetType;
    ConditionMethods: typeof ConditionMethods;
};
export default _default;
