"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NetworkProtocol = void 0;
var NetworkProtocol;
(function (NetworkProtocol) {
    NetworkProtocol[NetworkProtocol["StartGame"] = 0] = "StartGame";
    NetworkProtocol[NetworkProtocol["EndGame"] = 1] = "EndGame";
    NetworkProtocol[NetworkProtocol["StartTurn"] = 2] = "StartTurn";
    NetworkProtocol[NetworkProtocol["EndTurn"] = 3] = "EndTurn";
    NetworkProtocol[NetworkProtocol["PlayerState"] = 4] = "PlayerState";
    NetworkProtocol[NetworkProtocol["OpponentState"] = 5] = "OpponentState";
    NetworkProtocol[NetworkProtocol["QueuePlayCard"] = 6] = "QueuePlayCard";
    NetworkProtocol[NetworkProtocol["CardPlayed"] = 7] = "CardPlayed";
    NetworkProtocol[NetworkProtocol["CardMoved"] = 8] = "CardMoved";
    NetworkProtocol[NetworkProtocol["CardsMoved"] = 9] = "CardsMoved";
    NetworkProtocol[NetworkProtocol["PlayerAttacked"] = 10] = "PlayerAttacked";
    NetworkProtocol[NetworkProtocol["CreatureAttacked"] = 11] = "CreatureAttacked";
    NetworkProtocol[NetworkProtocol["AbilityActivated"] = 12] = "AbilityActivated";
    NetworkProtocol[NetworkProtocol["SendChatTextMessage"] = 13] = "SendChatTextMessage";
    NetworkProtocol[NetworkProtocol["BroadcastChatText"] = 14] = "BroadcastChatText";
    NetworkProtocol[NetworkProtocol["PlayerDrewCards"] = 15] = "PlayerDrewCards";
    NetworkProtocol[NetworkProtocol["OpponentDrewCards"] = 16] = "OpponentDrewCards";
    NetworkProtocol[NetworkProtocol["PlayerFinishedRecruiting"] = 17] = "PlayerFinishedRecruiting";
    NetworkProtocol[NetworkProtocol["NextPhaseReady"] = 18] = "NextPhaseReady";
    NetworkProtocol[NetworkProtocol["QueueFightCreature"] = 19] = "QueueFightCreature";
    NetworkProtocol[NetworkProtocol["PlayerReadyForQueue"] = 20] = "PlayerReadyForQueue";
    NetworkProtocol[NetworkProtocol["EndExecuteQueue"] = 21] = "EndExecuteQueue";
    NetworkProtocol[NetworkProtocol["QueueActivateAbility"] = 22] = "QueueActivateAbility";
    NetworkProtocol[NetworkProtocol["LandExplored"] = 23] = "LandExplored";
    NetworkProtocol[NetworkProtocol["LandTypeChanged"] = 24] = "LandTypeChanged";
    NetworkProtocol[NetworkProtocol["CardUpgraded"] = 25] = "CardUpgraded";
    NetworkProtocol[NetworkProtocol["QueueUpgradeCard"] = 26] = "QueueUpgradeCard";
    NetworkProtocol[NetworkProtocol["GetTargetsFromPlayer"] = 27] = "GetTargetsFromPlayer";
    NetworkProtocol[NetworkProtocol["ReturnTargetsToServer"] = 28] = "ReturnTargetsToServer";
    NetworkProtocol[NetworkProtocol["QueueStarted"] = 29] = "QueueStarted";
    NetworkProtocol[NetworkProtocol["PlayerExploredLand"] = 30] = "PlayerExploredLand";
    NetworkProtocol[NetworkProtocol["PlayerChangedLandType"] = 31] = "PlayerChangedLandType";
    NetworkProtocol[NetworkProtocol["CardIsBlocking"] = 32] = "CardIsBlocking";
    NetworkProtocol[NetworkProtocol["StopCardBlocking"] = 33] = "StopCardBlocking";
    NetworkProtocol[NetworkProtocol["ReorderBlockingCard"] = 34] = "ReorderBlockingCard";
    NetworkProtocol[NetworkProtocol["PlayerCardMovedRow"] = 35] = "PlayerCardMovedRow";
    NetworkProtocol[NetworkProtocol["ServerCardMovedRow"] = 36] = "ServerCardMovedRow";
    NetworkProtocol[NetworkProtocol["Test"] = 37] = "Test";
    NetworkProtocol[NetworkProtocol["RejoinedGame"] = 38] = "RejoinedGame";
    NetworkProtocol[NetworkProtocol["ServerSendingGamestateForRejoin"] = 39] = "ServerSendingGamestateForRejoin";
    NetworkProtocol[NetworkProtocol["CancelAction"] = 40] = "CancelAction";
})(NetworkProtocol || (NetworkProtocol = {}));
exports.NetworkProtocol = NetworkProtocol;
